# flutter github action workflow build and test flutter app on push and pull request to master branch and upload apk to github release on tag push and autorun on release
name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk --release
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload apk to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: MelonedApp.apk
          tag: ${{ github.ref }}
          overwrite: true

# Path: .github\workflows\main.yaml



